### ISSUE TITLE
Support reactxp routing or markdown parameters

### ISSUE THREAD

**Issue by vid** [Luxbyte/reactxp-markdown#1]
I'd like to use links for internal routing (if a link isn't using a uri scheme, go to an internal page), what's the best way to do that? Thanks!

**Comment by Fulanko** [comment]
I think this should be possible with deeplinking. Reactxp has support for [deeplinking](https://microsoft.github.io/reactxp/docs/apis/linking.html). That way you can use standard links in your markdown.

**Comment by vid** [comment]
I see the latest version makes this straightforward. Thanks!
