### ISSUE TITLE
React state update on unmounted component

### ISSUE THREAD

**Issue by vid** [Luxbyte/reactxp-markdown#3]
I get this one consistently:

![image](https://user-images.githubusercontent.com/68174/50973640-68b87300-14b7-11e9-99c1-4e606e3ac791.png)

It happens when I transition to a component (using reactxp's navigation) that has a markdown image. If I reload the page or load it directly, it doesn't have this problem.

Thanks!

**Comment by Fulanko** [comment]
I'm not sure what causes this warning. Are you unmounting the Markdown component immediately after mounting it? I added a safety check in the image component. Can you try if it works in version 0.0.6?

**Comment by vid** [comment]
With 0.0.6, there's no error, but the component doesn't display (it does display if I reload the page). The component shouldn't unmount, but I can't seem to add `componentWillUnmount` to verify since I get `Cannot invoke an object which is possibly 'undefined'`  in the `super.componentWillUnmount` call. If you have a suggestion I can try it, otherwise I will try to track this down in the next couple of days. Thank you.

**Comment by vid** [comment]
I haven't had a chance to look into this, but will close it since it could be an issue on my part.
